version: 0.2

env:
  variables:
    TF_VERSION: "1.1.5"

phases:

  install:
    runtime-versions:
       python: latest
    commands:
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip
      - python -V
      - pip3 install checkov

  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR"
      - checkov -d . --skip-check CKV_AWS_131,CKV_AWS_91,CKV_AWS_150,CKV_AWS_2,CKV_AWS_163,CKV_AWS_51,CKV_AWS_136,CKV_AWS_158,CKV_AWS_66,CKV_AWS_158,CKV_AWS_66,CKV_AWS_249,CKV_AWS_65,CKV_AWS_224,CKV_AWS_289,CKV_AWS_290,CKV_AWS_23,CKV_AWS_260,CKV_AWS_23,CKV_AWS_260,CKV_AWS_158,CKV_AWS_66,CKV_AWS_130,CKV2_AWS_20,CKV2_AWS_28,CKV_AWS_103,CKV_AWS_12

  post_build:
    commands:
      - echo "Checkov test is completed on `date`"