version: 0.2

env:
  variables:
    TF_VERSION: "1.1.5"

phases:

  install:
    runtime-versions:
       python: latest
    commands:
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip
      - python -V
      - pip3 install checkov

  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR"
      - checkov -d .

  post_build:
    commands:
      - echo "Checkov test is completed on `date`"